### ISSUE TITLE
Add git alias 'up'

### ISSUE THREAD

**Issue by velvolue** [veloek/dotfiles#1]
```
up = "!f() { git update-ref refs/heads/$1 refs/remotes/${2:-origin}/$1; }; f"
```

Git alias to reset a local branch to it's remote counterpart. Useful in combination with `fetch` after merging a large PR before switching back to main from the feature branch, e.g:
```sh
git fetch
git up main
git checkout main
```

Could possibly be improved to resolve the upstream ref dynamically in cases where the branch names differ, but it's not a big enough issue for me at least.

Also, would've liked to have the remote parameter (origin by default) as the first parameter if defined as that would've read better, but I didn't find a quick way to get that working. To explain better, these two commands should be equivalent:
```sh
git up main
git up origin main
```
But now you have to write:
```sh
git up main origin
```

**Comment by veloek** [comment]
Closed by 55049bbd79fa8b8ef1a1834874d8897c927d8c85
